export const roleMapper = {
    "CUW_TASK": "CUW Pool",
    "UW_TASK": "CUW Pool",
    "CMO_TASK": "CMO Pool",
    "CVT_TASK": "CVT Pool",
    "CPT_TASK": "CPT_TASK",
    "CPT_DATA_ENTRY_NMR_TASK": "CPT_TASK",
    "CPT_DATA_ENTRY_MR_TASK": "CPT_TASK",
    "DVT_TASK": "DVT Pool",
    "PIVV_TASK": "PIVV Pool",
    "PRE_ISSUANCE_SERVICING_TASK": "Pre Issuance Servicing Pool",
    "EXCEPTIONAL_TASK": "Exceptional Pool",
    "GUW_TASK": "GUW Pool",
    "HOD_TASK": "HOD Pool",
    "MMT_TASK": "MMT Pool",
    "SR_UW_TASK": "Sr UW Pool",
    "SUW_TASK": "SUW Pool",
    "VENDOR_CMO_TASK": "Vendor CMO Pool",
    "COPS_TASK": "COPS Pool",
    "IT_TASK": "IT Pool",
    "RI_TASK": "RI Pool",
    "SYSTEM_WAIT_POOL_AMR_MEDICAL": "System Wait Pool - Medical",
    "SYSTEM_WAIT_POOL_AMR_NON_MEDICAL": "System Wait Pool - Non Medical",
    "REQUIREMENT_POOL": "Requirement Pool",
    "CUW_CLAIM_AUDIT_TASK": "Claim Audit Pool",
    "ACCUITY_TASK": "Accuity Pool",
    "AMR_MEDICAL_TASK": "AMR_MEDICAL_TASK",
    "AMR_NON_MEDICAL_TASK": "AMR_NON_MEDICAL_TASK",
    "NON_MEDICAL_POOL": "AMR_NON_MEDICAL_TASK",

    "ECG_TASK": "ECG Pool",
    "TMT_TASK": "TMT Pool",
    "GRIEVANCE_TASK": "Grievance Pool",
    "RECONSIDERATION_TASK": "Reconsideration Pool",
    "REJECT_TASK": "Reject Pool",
    "READY_FOR_ISSUANCE_TASK": "Ready For Issuance Pool",

    "GUW_FORMAL_TASK": "GUW_FORMAL_TASK",
    "DVT_FORMAL_TASK": "DVT_FORMAL_TASK",
    "RISK_TASK": "RISK_TASK",
    "ACUITY_TASK": "ACUITY_TASK"
};